# CloudFormation template that deploys SNS topic, Lambda Function, EventBridge
AWSTemplateFormatVersion: "2010-09-09"
Description: Troubleshooting Cloudformation Failures with Generative AI

Parameters:
  EmailAddress:
    Type: String
    Description: Email addresses of the subscriber
  SecondEmailAddress:
    Type: String
    Default: ''
    Description: (Optional) Secondary email address for notifications
  FunctionName:
    Type: String
    Default: LambdaStackFailureAssistant
  Runtime:
    Type: String
    Default: python3.10
  S3BucketLambdaLayer:
    Type: String
  S3FileName:
    Type: String
    Default: python.zip

  # Condition to check if SecondEmailAddress is provided
Conditions:
  HasSecondEmailAddress: !Not [!Equals [!Ref SecondEmailAddress, '']]

Resources:
# SNS Email Topic
  SNSEmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: email
      Tags:
        - Key: project
          Value: troubleshooting-cloudformation-failures
  
  # Second Email Subscription (if SecondEmailAddress is provided)
  SecondEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasSecondEmailAddress
    Properties:
      TopicArn: !Ref SNSEmailTopic
      Protocol: email
      Endpoint: !Ref SecondEmailAddress

# Lambda Role that has invokes Bedrock and SNS permissions
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${FunctionName}-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: BedrockInvokePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "bedrock:InvokeModel"
                  - "bedrock:InvokeModelWithResponseStream"
                Resource: "*"
        - PolicyName: SNSPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "sns:Publish"
                Resource: !Ref SNSEmailTopic
        - PolicyName: LambdaLogging
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
      Tags:
        - Key: project
          Value: troubleshooting-cloudformation-failures

# Lambda Layer 
  LambdaBoto3Layer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.10
      Content:
        S3Bucket: !Ref S3BucketLambdaLayer
        S3Key: !Ref S3FileName
      Description: Boto3 lambda layer
      LayerName: boto3-lambda-layer
      LicenseInfo: MIT
  
  # Lambda Function that is invoked by EventBridge
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: index.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: !Ref Runtime
      Timeout: 300
      Code:
        ZipFile: |
          import os
          import boto3
          import json


          TOPIC_ARN = os.environ["TOPIC_ARN"]
          REGION = os.environ["REGION"]

          # Define bedrock
          bedrock = boto3.client(
              service_name="bedrock-runtime",
              region_name=REGION
          )

          sns = boto3.client(
                  service_name="sns",
                  region_name=REGION
              )


          def create_prompt(reason: str, stack_name: str) -> str:
              prompt = f"""Dear customer,

              The following CloudFormation Template {stack_name} in {REGION} has failed. I have analyzed the template and here is the failure reason provided: {reason}. 
              
              The root cause appears to be <root_cause>. 
              
              <explain analysis and reasoning>.
              
              To resolve this issue, I would suggest the following next steps:
              
                  <step 1>
                  <step 2>
                  <step 3>
                  etc....
              
              Please let me know if any of those steps need further clarification or if you have additional questions. I'm happy to provide more details if needed.
              
              Thank you, 
              
              Claude
              """
              return prompt


          def send_prompt(prompt: str): 
              prompt_config = {
                  "anthropic_version": "bedrock-2023-05-31",
                  "max_tokens": 4096,
                  "messages": [
                      {
                          "role": "user",
                          "content": [
                              {
                              "type": "text",
                              "text": prompt
                              }
                          ]
                      }
                  ]
              }

              body = json.dumps(prompt_config)

              modelId = "anthropic.claude-3-sonnet-20240229-v1:0"
              contentType = "application/json"
              accept = "application/json"
              response = bedrock.invoke_model(
                  body=body, modelId=modelId, accept=accept, contentType=contentType
              )
              response_body = json.loads(response.get("body").read())

              result = response_body.get("content")[0]["text"]
              return result

          # Create a function that send text to trigger sns
          def send_text(message: str):
              sns.publish(
                  TopicArn=TOPIC_ARN,
                  Message=message
              )
              return "SNS Successfully SENT"


          # Lambda handler
          def lambda_handler(event, context):
              print("Received event")
              reason = event["detail"]["status-details"]["status-reason"]
              arn = event["detail"]["stack-id"]
              components = arn.split('/')
              stack_name = components[1]
              prompt = create_prompt(reason, stack_name)
              response = send_prompt(prompt)
              sns_response = send_text(response)
              print(sns_response)
              return sns_response
      Layers:
        - !Ref LambdaBoto3Layer
      Environment:
        Variables:
          REGION: !Ref "AWS::Region"
          TOPIC_ARN: !Ref "SNSEmailTopic"
          STACK_NAME: !Ref "AWS::StackName"
      Tags:
        - Key: project
          Value: troubleshooting-cloudformation-failures

# EventBridge Rule that triggers Lambda Function
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventBridgeRule"
      State: "ENABLED"
      EventPattern:
        source:
          - "aws.cloudformation"
        detail-type:
          - "CloudFormation Resource Status Change"
        region:
          - !Ref "AWS::Region"
        detail:
          status-details:
            status:
              - "CREATE_FAILED"
              - "UPDATE_FAILED"
              - "DELETE_FAILED"
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: "TargetFunctionV1"
  
  # Permission that allows EventBridge to invoke Lambda
  EventRuleInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "EventBridgeRule"
          - "Arn"
        